### ISSUE TITLE
Connect to a session that already exist?!

### ISSUE THREAD

**Issue by argenisleon** [Yuhsak/livy-client#1]
Hi,

I am creating a session in a cluster from a backend app and I need another app to send a statement to that session. Is there a way in which I can tell livy-client to connect to a specific session?

**Comment by yuhsak** [comment]
If you know the session id you want to connect, how about trying this?

```js
const livy = new LivyClient({
  host: 'your-host',
  port: '8998'
})

const session = livy.session({id: 'your-session-id'})

session
  .run('print("hi")', {autoupdate: true})
  .once('available', r => console.log(r.output))
```
