### ISSUE TITLE
Running Python Script

### ISSUE THREAD

**Issue by pfarah65** [Yuhsak/livy-client#2]
Hey, I'm having trouble trying to run a .py script located locally. I tried the following command.
`        const newSession = await livy.createSession({
          kind: 'pyspark',
          numExecutors: 1,
          pyFiles: ["./test.py"],
        })`
When I look at the logs it doesn't even execute the script. What am I doing wrong?

**Comment by yuhsak** [comment]
Hi!

First, According to spark-submit with --py-files option, the pyFiles must be located on spark cluster (probably on master node), not on your local in which you execute node.js script.

While apache livy has no function to send files to spark cluster from your local, you have to do it manually before you use livy to create session with pyfiles.

Second, do you want to execute existing python script with apache livy? Then I recommend you to use Batch interface instead.
`livy.createSession` is normally for interactive usage.
If your script depends on any other script, you could specify the location with pyFiles option.
Also make sure you locate your files on spark cluster.

```js
const LivyClient = require('livy-client')
const livy = new LivyClient({host: 'your-livy-host', port: 8998})
const {Batch} = livy
const session = Batch.createSession({file: 'your-main-script.py', pyFiles: 'your-library.py'})

session.on('update', console.log)
```

I hope this helps :)

**Comment by pfarah65** [comment]
Thanks I think I got it working 👍 
Also you had a typo 
`const Batch = livy.Batch()` :)
